apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "identree.fullname" . }}
  labels:
    {{- include "identree.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.database.driver "postgres" }}
  maxUnavailable: 1
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "identree.selectorLabels" . | nindent 6 }}
