#!/bin/bash
# setup.sh — configure Kanidm for the identree test environment.
# Run after: make test-kanidm
#
# What this does:
#   1. Recovers the admin account (resets to a generated password)
#   2. Authenticates via Kanidm REST API to get a bearer token
#   3. Creates POSIX groups: developers (gid=20001), admins (gid=20002)
#   4. Creates POSIX users: alice (uid=10001), bob (uid=10002), testadmin (uid=10003)
#   5. Assigns group membership
#   6. Creates the identree-test OAuth2/OIDC client
#   7. Configures scope maps so groups appear in tokens
#   8. Outputs KANIDM_CLIENT_SECRET
#
# kanidmd (daemon) commands run via docker exec into the server container.
# kanidm (client) commands run via docker run using kanidm/tools:latest, which
# contains the client CLI. The tools container connects to the server over the
# Docker-internal network (kanidm_default) using the service hostname "kanidm".
#
# kanidm login requires /dev/tty (rpassword), which is not available in CI
# non-interactive Docker containers. We authenticate via the Kanidm REST API
# from the host instead and pass the bearer token via KANIDM_AUTH_TOKEN.
set -euo pipefail

KC_URL="https://localhost:8443"
CONTAINER="identree-kanidm-server"
NETWORK="kanidm_default"
TOOLS_IMAGE="docker.io/kanidm/tools:latest"
# Named volume containing the CA cert generated by the init-certs service.
CERTS_VOLUME="kanidm_kanidm-certs"

# Temp dir on the host for the kanidm client session token cache.
KANIDM_HOME=$(mktemp -d)
trap 'rm -rf "${KANIDM_HOME}"' EXIT

# ── Helpers ────────────────────────────────────────────────────────────────────

wait_for() { echo "==> Waiting for ${2}..."; until curl -skf "$1" >/dev/null 2>&1; do sleep 2; done; echo "    ${2} ready."; }

# Run a kanidm CLI command using the tools image.
# The tools container joins the kanidm Docker network so it can reach
# the server at https://kanidm:8443 using the Docker-internal hostname.
# KANIDM_AUTH_TOKEN and KANIDM_CA_PATH are passed from the host environment.
ke() {
    docker run --rm \
        --network "${NETWORK}" \
        -v "${KANIDM_HOME}:/kanidm-home" \
        -v "${CERTS_VOLUME}:/certs:ro" \
        -e HOME="/kanidm-home" \
        -e KANIDM_CA_PATH="/certs/ca.crt" \
        -e KANIDM_AUTH_TOKEN="${ADMIN_TOKEN}" \
        "${TOOLS_IMAGE}" \
        kanidm "$@" -H "https://kanidm:8443" 2>&1
}

# ── Wait for Kanidm ────────────────────────────────────────────────────────────
wait_for "${KC_URL}/status" "Kanidm"

# ── Recover admin account ──────────────────────────────────────────────────────
# kanidmd recover-account resets the account password and prints the new one.
# We recover 'admin' (system superadmin) which can manage persons, groups,
# POSIX attributes, and OAuth2 clients.
echo "==> Recovering admin account..."
ADMIN_RECOVERY=$(docker exec "${CONTAINER}" \
    kanidmd recover-account admin 2>&1 || true)

# Extract the generated password — try "Password: <value>" first, then fall back
# to any 20+ char alphanumeric token as a last resort.
ADMIN_PW=$(printf '%s' "$ADMIN_RECOVERY" | grep -oP '(?<=Password: )\S+' 2>/dev/null | head -1 || true)
if [ -z "$ADMIN_PW" ]; then
    ADMIN_PW=$(printf '%s' "$ADMIN_RECOVERY" | grep -i 'password' | grep -oE '[A-Za-z0-9]{20,}' | head -1 || true)
fi

if [ -z "$ADMIN_PW" ]; then
    echo "ERROR: Could not extract admin password from recover-account output."
    echo "Recovery output:"
    echo "$ADMIN_RECOVERY"
    echo ""
    echo "Try manually: docker exec ${CONTAINER} kanidmd recover-account admin"
    exit 1
fi
echo "    admin recovered."

# ── Authenticate via Kanidm REST API ──────────────────────────────────────────
# kanidm login requires /dev/tty (rpassword library) which is not available
# in CI containers run without a pseudo-TTY. We use the Kanidm REST API
# directly to get a bearer token, then pass it as KANIDM_AUTH_TOKEN.
echo "==> Authenticating as admin via Kanidm REST API..."

# Kanidm AuthStep enum uses #[serde(rename_all = "lowercase")] so all variant
# names and inner enum values must be lowercase in the JSON body.

# Step 1: Init auth session
INIT_RESP=$(curl -sk -X POST "${KC_URL}/v1/auth" \
    -H "Content-Type: application/json" \
    -d '{"step":{"init2":{"username":"admin","issue":"token","privileged":false}}}')
echo "    Init response: $INIT_RESP"
SESSION_ID=$(printf '%s' "$INIT_RESP" | \
    python3 -c "import sys,json; print(json.load(sys.stdin)['sessionid'])" 2>/dev/null || echo "")

if [ -z "$SESSION_ID" ]; then
    echo "ERROR: Failed to init auth session."
    exit 1
fi

# Step 2: Select Password mechanism
curl -sk -X POST "${KC_URL}/v1/auth" \
    -H "Content-Type: application/json" \
    -H "X-KANIDM-AUTH-SESSION-ID: ${SESSION_ID}" \
    -d '{"step":{"begin":"password"}}' >/dev/null

# Step 3: Submit password credential → receive bearer token
CRED_RESP=$(curl -sk -X POST "${KC_URL}/v1/auth" \
    -H "Content-Type: application/json" \
    -H "X-KANIDM-AUTH-SESSION-ID: ${SESSION_ID}" \
    -d "{\"step\":{\"cred\":{\"password\":\"${ADMIN_PW}\"}}}")
echo "    Cred response: $(printf '%s' "$CRED_RESP" | python3 -c "import sys,json; d=json.load(sys.stdin); print({k: v[:20]+'...' if isinstance(v,str) and len(v)>20 else v for k,v in d.items()})" 2>/dev/null || echo "$CRED_RESP")"

ADMIN_TOKEN=$(printf '%s' "$CRED_RESP" | python3 -c "
import sys, json
d = json.load(sys.stdin)
state = d.get('state', {})
if isinstance(state, dict) and 'Success' in state:
    print(state['Success'])
" 2>/dev/null || echo "")

if [ -z "$ADMIN_TOKEN" ]; then
    echo "ERROR: Failed to get admin bearer token."
    echo "Credential response: $CRED_RESP"
    exit 1
fi
echo "    admin authenticated."

# ── Create groups with POSIX GIDs ─────────────────────────────────────────────
echo "==> Creating groups..."
ke group create developers || true
ke group create admins     || true

ke group posix-set developers --gid 20001 || true
ke group posix-set admins     --gid 20002 || true

# ── Create users with POSIX attributes ────────────────────────────────────────
echo "==> Creating users..."

# person create <loginname> <display name>
ke person create alice     "Alice Liddell"  || true
ke person create bob       "Bob Builder"    || true
ke person create testadmin "Test Admin"     || true

# Enable POSIX attributes — required for sssd to resolve UID/GID/shell/home
ke person posix-set alice     --uid 10001 --gid 20001 --shell /bin/bash --home /home/alice     || true
ke person posix-set bob       --uid 10002 --gid 20001 --shell /bin/bash --home /home/bob       || true
ke person posix-set testadmin --uid 10003 --gid 20002 --shell /bin/bash --home /home/testadmin || true

# ── Assign group membership ────────────────────────────────────────────────────
echo "==> Assigning group membership..."
ke group add-members developers alice bob     || true
ke group add-members admins     testadmin     || true

# ── Create OAuth2/OIDC client ──────────────────────────────────────────────────
echo "==> Creating OAuth2 client identree-test..."
# Kanidm OAuth2 client: name, display name, redirect URI
ke system oauth2 create identree-test "identree (test)" \
    "http://localhost:8093/callback" || true

# Add the Docker-internal redirect URI
ke system oauth2 update-redirect-url identree-test \
    "http://identree:8090/callback" || true

# Configure scope maps: which groups get which scopes in the token.
# identree needs the 'groups' scope to see group membership.
for group in developers admins; do
    ke system oauth2 update-scope-map identree-test "${group}" \
        openid profile email groups || true
done

# Retrieve the client secret
CLIENT_SECRET=$(ke system oauth2 show-basic-secret identree-test 2>&1 | \
    grep -oE '[A-Za-z0-9+/=_-]{20,}' | head -1 || echo "")

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Kanidm test environment ready"
echo ""
echo "  Services:"
echo "    Kanidm:    https://localhost:8443   (admin recovered above)"
echo "    identree:  http://localhost:8093"
echo "    LDAP:      ldap://localhost:3636   base=dc=test,dc=local"
echo ""
echo "  OIDC client credentials:"
echo "    client_id:     identree-test"
echo "    client_secret: ${CLIENT_SECRET:-<retrieve manually: ke system oauth2 show-basic-secret identree-test>}"
echo ""
echo "  Set user passwords (required for Kanidm web login):"
echo "    docker run --rm -it --network ${NETWORK} -v ${CERTS_VOLUME}:/certs:ro -e KANIDM_CA_PATH=/certs/ca.crt ${TOOLS_IMAGE} kanidm person credential create-reset-token alice -H https://kanidm:8443"
echo "    (follow the reset link to set alice's password)"
echo ""
echo "  Restart identree with the client secret:"
echo "    KANIDM_CLIENT_SECRET=${CLIENT_SECRET:-<secret>} \\"
echo "    docker compose -f test/providers/kanidm/docker-compose.yml up -d identree"
echo ""
echo "  Validate:"
echo "    docker exec identree-kanidm-client getent passwd alice"
echo "    docker exec identree-kanidm-client getent group developers"
echo "    docker exec -it identree-kanidm-client bash"
echo "    sudo whoami  (as alice → triggers identree PAM challenge)"
echo "════════════════════════════════════════════════════════════"
